name: Build and deploy Node.js app to Azure Web App - cv-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies (only prod)
        run: npm ci --omit=dev

      - name: Build NestJS app
        run: npm run build

      - name: Prepare app for deployment
        run: |
          mkdir -p deploy
          cp -r dist package.json package-lock.json deploy/
          cd deploy
          npm ci --omit=dev  # instala solo las dependencias necesarias para producción
          cd ..

      - name: Zip app for deployment
        run: cd deploy && zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1C8BDACF5CFF40739D8A1A202574E0DF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_687569197F464D05ACD7EE99EE2070C9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9034D311E51045B0A790774C4453D625 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cv-back'
          slot-name: 'Production'
          package: release.zip
